sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t besteban/jenkins-arm .
# test image
- docker run besteban/jenkins-arm
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV JENKINS_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag jenkins-arm jenkins-arm:$TAG
    docker push jenkins-arm:$TAG
    docker push jenkins-arm
  fi